In [4]:
import pandas as pd
import numpy as np

# 1

df = pd.DataFrame({"X" : [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

y = [0]

for x in range(len(df["X"])):
	for z in range(x - 1, -1, -1):
		if z == 0:
			y.append(x)
			break
		elif df["X"][z] == 0:
			y.append(x - z)
			break
df["Y"] = y
print(df)


# 2

idx = pd.bdate_range('2015-01-01', '2015-12-31')

df1 = pd.DataFrame(index=idx)

df1['rand'] = np.random.randint(1, 1000, size=len(df1))

print (df1)

#3


print (df1.loc[pd.bdate_range('2015-01-07', '2015-12-31', freq="7D")].sum()) # suma de valores de todos los miercoles

#4

print( df1.groupby(df1.index.month)[['rand']].agg('mean')) # media por mes

#5

print (df1.groupby(pd.Grouper(freq="4M", base=3))[['rand']].agg('max')) #maximo por 4 meses

   X  Y
0  7  0
1  2  1
2  0  2
3  3  1
4  4  2
5  2  3
6  5  4
7  0  5
8  3  1
9  4  2
            rand
2015-01-01   657
2015-01-02   165
2015-01-05    32
2015-01-06   313
2015-01-07   899
2015-01-08   561
2015-01-09   455
2015-01-12   802
2015-01-13   324
2015-01-14    57
2015-01-15   197
2015-01-16   537
2015-01-19   397
2015-01-20   512
2015-01-21   480
2015-01-22   394
2015-01-23   657
2015-01-26   229
2015-01-27   850
2015-01-28   964
2015-01-29   306
2015-01-30   760
2015-02-02    95
2015-02-03   232
2015-02-04   263
2015-02-05   475
2015-02-06   126
2015-02-09   147
2015-02-10   515
2015-02-11   506
...          ...
2015-11-20   597
2015-11-23    99
2015-11-24   304
2015-11-25   575
2015-11-26   303
2015-11-27   524
2015-11-30   763
2015-12-01   449
2015-12-02    11
2015-12-03   239
2015-12-04   157
2015-12-07   588
2015-12-08   411
2015-12-09   321
2015-12-10   738
2015-12-11   927
2015-12-14   945
2015-12-15   322
2015-12-16   211
2015-12-17   601
2015-12-18   236
2015-12-21   487
2015-12-22   600
2015-12-23   288
2015-12-24   756
2015-12-25   588
2015-12-28    80
2015-12-29   237
2015-12-30   232
2015-12-31   857

[261 rows x 1 columns]
rand    24272
dtype: int64
          rand
1   479.454545
2   465.050000
3   427.727273
4   635.818182
5   500.333333
6   511.590909
7   515.173913
8   645.666667
9   461.318182
10  506.409091
11  444.428571
12  447.000000
            rand
2015-01-31   964
2015-05-31   981
2015-09-30   991
2016-01-31   962